apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: j4kdemo
  name: j4kdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: j4kdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: j4kdemo
    spec:
      containers:
        - image: acrjuduboisj4kdemo001.azurecr.io/judubois-j4kdemo/judubois-j4kdemo:latest
          name: j4kdemo
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILE
              value: prod
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datasource-credentials
                  key: SPRING_DATASOURCE_PASSWORD
          resources: {}
